### ISSUE TITLE
Wrapping around any KVO-backed classes

### ISSUE THREAD

**Issue by jboo1212** [CharlesJS/CSProgress#2]
Have you considered this?  I had to deal with AVPlayer and could see a lot of folks benefiting from this.

**Comment by CharlesJS** [comment]
Hi jboo1212,

Could you please give a little more detail as to what you have in mind? Thanks!

**Comment by jboo1212** [comment]
So CSProgress was to eliminate the need of KVO-backing for NSProgress, but what if this could be applied to any KVO-backed class?
<img width="883" alt="screen shot 2018-10-05 at 2 52 29 pm" src="https://user-images.githubusercontent.com/8954137/46561850-4a3a4e80-c8ae-11e8-8061-e5c0f96569c6.png">

**Comment by CharlesJS** [comment]
CSProgress isn't a wrapper around NSProgress, though—it's a complete from-scratch reimplementation of NSProgress. It has the ability to bridge to NSProgress so that you can integrate with existing progress trees, yes, but if you just use CSProgress by itself, it's pure Swift all the way down. I didn't just want to avoid dealing with KVO's interface, I wanted to build a better-performing solution by, among other things, avoiding KVO notifications being sent _at all_, which you can't do just by wrapping. So, I'm not sure exactly what you're asking for.
